services:
  yjv.report_rendering.column:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\Type\ColumnType
    tags:
      - { name: 'yjv.column_type' }
  
  yjv.report_rendering.escaped_column:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\Type\EscapedColumnType
    tags:
      - { name: 'yjv.column_type' }
  
  yjv.report_rendering.property_path_column:
    class: Yjv\Bundle\ReportRenderingBundle\Renderer\Grid\Column\Type\PropertyPathType
    tags:
      - { name: 'yjv.column_type' }